server:
  port: 8080

com:
  labforward:
    docs:
      title: Labforward Similarities
      description: API Documentation Labforward Similarities.
      base-package: com.labforward
      version: 1.0.0
      contact: khaled Mosaad Mohamed <engkhaledmos3ad@gmail.com>